### ISSUE TITLE
Using the Color type from avh4/elm-color for the 0.19 upgrade.

### ISSUE THREAD

**Issue by RalfNorthman** [dawehner/elm-colorbrewer#1]
I propose that we use the Color type from avh4/elm-color when upgrading to 0.19. That package is the 0.19 replacement for the Color package that was part of Core in 0.18.

https://package.elm-lang.org/packages/avh4/elm-color/latest/

Perhaps I will have time to do the upgrade. I don't think it will be too much work.

**Comment by dawehner** [comment]
That seems 100% sensible. I'd happily accept a PR, but I might also just do
it myself

**Comment by RalfNorthman** [comment]
In the main branch (v3.0.1) we have integer tuples to represent the colors and in "my" branch (which diverged before your 0.19 upgrade) we use the Color type from `avh4/elm-color`. I would say that the Color solution is better (which is also how your package did it back in 0.18, but with `elm-lang/core/color`). 

What do you think? How do we move forward?

**Comment by dawehner** [comment]
I totally agree with you

* Let's switch to elm-color instead of tuples
* Let's then figure out the API for the collection of colours.

Does that sound like a good plan?

**Comment by RalfNorthman** [comment]
Alright, sounds good. Pull request coming real soon.
