### ISSUE TITLE
Change API for color set functions to take an integer (of colors to return) as an argument.

### ISSUE THREAD

**Issue by RalfNorthman** [dawehner/elm-colorbrewer#2]
I'm thinking an API along the lines of `set2 : Int -> List Color` instead of `set23 : List Color`, `set24 : List Color` and so forth. With this we could eliminate some duplication in the code by defining each color set just once and using `List.take` on it. This makes it easier to use the package if you don't know beforehand how many colors you need. Also: I think it will be clearer that it is "three from set two", not "set twentythree" with this change.

I could take upon myself to implement this if it is desired.

Awesome initiative to bring these great data visualisation palettes to Elm!

**Comment by RalfNorthman** [comment]
I guess my proposed API will lead to some problems if used as is. We would have to return the empty list for arguments less than one, but that is not as big of a problem as returning the entire palette with length *n* when the argument is greater than *n*. That might lead to unanticipated behaviour for the user. For example: they expect a list of length 12, but get 10. 

Alternatively we cycle the palette so the overflow takes colors from the beginning of the list. But that is not super-intuitive and seldom useful in a plotting context. This is the second option.

None of these two are optimal, but I'm not happy with the API as it is either. Is it reasonable to expect the user to check the maximum number of colors in a palette? 

What is more desirable: to always get a list back that has the same length as the input (at least when the argument is positive) **or** never get duplicate colors?

A third option is to return a Maybe. Return `Nothing` when the argument is out of range, but that seems a bit clunky.

I'm leaning towards the first option, which happens to be the behaviour of `List.take`.

**Comment by dawehner** [comment]
@RalfNorthman 
I've adopted the generated code to include a function like `set2 : Int -> List Color`. It is using as much information as what is available when generating the color file. As long the elm compiler gets rids of as much as possible code on compile time this approach seems doable.

Please try out the version 4.1.0 :)
